apiVersion: v1
kind: Namespace
metadata:
  name: nginxhello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello # names the deployment?
  namespace: nginxhello
spec:
  selector:
    matchLabels:
      app: nginxhello # matches the below template?
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxhello # what the service matches against?
    spec:
      containers:
        - name: nginxhello
          image: nginxdemos/hello
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxhello
  namespace: nginxhello
spec:
  selector:
    app: nginxhello # matches deployment.spec.template.metadata.labels.app?
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxhello
  namespace: nginxhello
spec:
  rules:
    - host: scaena.sudov.im
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginxhello # matches service.metadata.name?
                port:
                  number: 80
